# Generated by Django 5.0.4 on 2024-04-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_veterinario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
