# Generated by Django 5.0.4 on 2024-04-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthday',
            field=models.CharField(default='', max_length=40),
        ),
    ]
