# Generated by Django 5.0.4 on 2024-04-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product'),
        ('app', '0005_pet_birthday'),
    ]

    operations = [
    ]
