# Generated by Django 5.0.4 on 2024-05-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_veterinary'),
        ('app', '0007_medicine'),
    ]

    operations = [
    ]
