# Generated by Django 5.0.4 on 2024-05-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_0004_veterinary_0007_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
