# Generated by Django 5.0.4 on 2024-05-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_price'),
        ('app', '0008_merge_0004_veterinary_0007_medicine'),
    ]

    operations = [
    ]
