# Generated by Django 5.0.4 on 2024-05-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20240524_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
