# Generated by Django 5.0.4 on 2024-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
