# Generated by Django 5.0.4 on 2024-05-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20240526_1658'),
        ('app', '0009_provider_address'),
        ('app', '0010_alter_pet_birthday'),
        ('app', '0010_pet_weight'),
    ]

    operations = [
    ]
