# Generated by Django 5.0.4 on 2024-05-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_provider_address'),
        ('app', '0010_alter_pet_birthday'),
    ]

    operations = [
    ]
