# Generated by Django 5.0.4 on 2024-05-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_0009_provider_address_0010_alter_pet_birthday'),
        ('app', '0011_merge_20240526_2352'),
    ]

    operations = [
    ]
