# Generated by Django 5.0.4 on 2024-06-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20240602_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(),
        ),
    ]
