# Generated by Django 5.0.4 on 2024-06-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_veterinario_phone'),
        ('app', '0012_merge_20240527_1731'),
    ]

    operations = [
    ]
