# Generated by Django 5.0.4 on 2024-06-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_product_type_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
