# Generated by Django 5.0.4 on 2024-06-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_product_price'),
        ('app', '0014_merge_20240603_0914'),
    ]

    operations = [
    ]
