# Generated by Django 5.0.4 on 2024-06-05 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240603_1125'),
        ('app', '0015_merge_20240603_1806'),
        ('app', '0015_merge_20240604_1813'),
        ('app', '0015_merge_20240604_1908'),
        ('app', '0015_merge_20240604_2040'),
        ('app', '0015_merge_20240604_2051'),
        ('app', '0015_merge_20240605_1156'),
    ]

    operations = [
    ]
