# Generated by Django 5.0.4 on 2024-06-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240603_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
