# Generated by Django 5.0.4 on 2024-06-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240604_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veterinario',
        ),
    ]
