# Generated by Django 5.0.4 on 2024-06-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20240605_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Veterinario',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('La Plata', 'La Plata'), ('Berisso', 'Berisso'), ('Ensenada', 'Ensenada')], default=6969, max_length=35),
            preserve_default=False,
        ),
    ]
