# Generated by Django 5.0.4 on 2024-06-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_city'),
        ('app', '0015_merge_20240603_1125'),
        ('app', '0016_delete_veterinario'),
    ]

    operations = [
    ]
