# Generated by Django 5.0.4 on 2024-06-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_veterinario_remove_client_address_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
