# Generated by Django 5.0.4 on 2024-06-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20240605_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('La Plata', 'La Plata'), ('Berisso', 'Berisso'), ('Ensenada', 'Ensenada')], default=1, max_length=35),
            preserve_default=False,
        ),
    ]
