# Generated by Django 5.0.4 on 2024-06-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_medicine_image_url_alter_medicine_description'),
        ('app', '0018_alter_client_phone_alter_veterinary_phone'),
    ]

    operations = [
    ]
