# Generated by Django 5.0.4 on 2024-06-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_merge_20240604_2359'),
        ('app', '0018_remove_client_address_client_city'),
    ]

    operations = [
    ]
