# Generated by Django 5.0.4 on 2024-06-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240603_1806'),
        ('app', '0015_merge_20240604_1813'),
        ('app', '0019_merge_20240605_0942'),
    ]

    operations = [
    ]
