# Generated by Django 5.0.4 on 2024-06-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20240616_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
