# Generated by Django 5.0.4 on 2024-06-17 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_client_phone_alter_veterinary_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client'),
        ),
    ]
