# Generated by Django 5.0.4 on 2024-06-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20240605_1156'),
        ('app', '0020_merge_20240605_1018'),
    ]

    operations = [
    ]
