# Generated by Django 5.0.4 on 2024-06-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_pet_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='medicines',
            field=models.ManyToManyField(to='app.medicine'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vets',
            field=models.ManyToManyField(blank=True, to='app.veterinary'),
        ),
    ]
