# Generated by Django 5.0.4 on 2024-06-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_pet_medicines_pet_vets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vets',
            new_name='veterinaries',
        ),
    ]
