# Generated by Django 5.0.4 on 2024-06-25 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_product_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(choices=[('La Plata', 'La Plata'), ('Berisso', 'Berisso'), ('Ensenada', 'Ensenada'), ('Avellaneda', 'Avellaneda'), ('Lomas de Zamora', 'Lomas De Zamora'), ('Morón', 'Moron'), ('Tigre', 'Tigre'), ('Vicente López', 'Vicente Lopez'), ('San Isidro', 'San Isidro'), ('Banfield', 'Banfield'), ('Florida', 'Florida'), ('Quilmes', 'Quilmes'), ('La Matanza', 'La Matanza'), ('Ezeiza', 'Ezeiza'), ('Lanús', 'Lanus'), ('Merlo', 'Merlo'), ('Moreno', 'Moreno'), ('San Miguel', 'San Miguel'), ('Tres de Febrero', 'Tres De Febrero'), ('Lobos', 'Lobos'), ('Pilar', 'Pilar'), ('San Fernando', 'San Fernando'), ('San Martín', 'San Martin'), ('Tres Arroyos', 'Tres Arroyos'), ('Zárate', 'Zarate')], max_length=35),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.client'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
