# Generated by Django 5.0.4 on 2024-07-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_client_city_alter_medicine_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='tag',
        ),
    ]
